ALTER TABLE "ncrs"
    ADD COLUMN IF NOT EXISTS "reviewed_by" UUID REFERENCES "users"("id") ON DELETE SET NULL;
ALTER TABLE "ncrs"
    ADD COLUMN IF NOT EXISTS "reviewed_at" TIMESTAMPTZ;
ALTER TABLE "ncrs"
    ADD COLUMN IF NOT EXISTS "closed_by" UUID REFERENCES "users"("id") ON DELETE SET NULL;
